name = "notion-backups"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-29"
[triggers]
crons = ["0 0 * * *"]
#[secrets]
#TOKEN_V2
#SLACK_WEBHOOK
#DISCORD_WEBHOOK
#EXPORTTYPE
#LOCALE
#TIMEZONE
#MODE
